name: Update NAVs Daily

on:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM UTC
  workflow_dispatch:

jobs:
  update-nav:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode and save service account key
        run: echo "${{ secrets.GO_SERVICE_ACCOUNT_KEY }}" > service_account.json

      - name: Run NAV updater
        run: python nav_updater.py
